### Create User
POST http://localhost:8080/users/createUser
Content-Type: application/json

{
  "id": 1,
  "name": "Johny",
  "email": "johny@test.com",
  "age": 25
}
###

### Create User
POST http://localhost:8080/users/createUsers
Content-Type: application/json

[
  {
    "id": 2,
    "name": "John",
    "email": "john@test.com",
    "age": 26
  },
  {
    "id": 3,
    "name": "Jane",
    "email": "jane@test.com",
    "age": 27
  }
]
###

### Get All Users
GET http://localhost:8080/users
###

### Get User By Id
GET http://localhost:8080/users/2
###

### Delete User (change id if needed)
DELETE http://localhost:8080/users/3
###

### Delete All Users
DELETE http://localhost:8080/users

